FROM ubuntu:18.04

MAINTAINER tommytyc

RUN apt-get update
RUN apt-get install -y iptables
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install -y tcpdump
RUN apt-get install -y vim 
RUN apt-get install -y sudo 
RUN apt-get install -y git
RUN apt-get install -y isc-dhcp-server
RUN apt-get install -y isc-dhcp-client
RUN apt-get install -y mininet
