FROM ubuntu:18.04

MAINTAINER tommytyc

RUN apt-get -y update
RUN apt-get install -y iptables
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install -y tcpdump
RUN apt-get install -y vim
RUN apt-get install -y isc-dhcp-server
RUN apt-get install -y isc-dhcp-client
RUN apt-get install -y bridge-utils
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y flex bison
RUN apt-get install -y make
RUN apt-get install -y netcat